version: '3.1'

services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: test
      POSTGRES_DB: test42
    
    ports:
      - '8080:5432'  

   
   